PetCommunityWeb/PetCommunityBack

src/main/java/com/example/petback/common/config/WebSecurityConfig.java, src/main/java/com/example/petback/common/security/JwtAuthenticationFilter.java, src/main/java/com/example/petback/user/controller/UserController.java, src/main/java/com/example/petback/user/dto/LoginRequestDto.java, src/main/java/com/example/petback/user/dto/SignupRequestDto.java, src/main/java/com/example/petback/user/entity/User.java, src/main/java/com/example/petback/user/service/UserService.java
로그인 회원가입 관련  security 설정에서 url주소와, 권한설정 등 수정 했습니다.
회원가입관련 api도 추가해놨습니다. (userController 확인)
=> fix: 로그인, 회원가입 관련 수정

src/main/java/com/example/petback/common/domain/Address.java, src/main/java/com/example/petback/hospital/controller/HospitalController.java, src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java, src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/hospital/repository/HospitalRepository.java, src/main/java/com/example/petback/hospital/service/HospitalService.java, src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java, src/main/java/com/example/petback/user/entity/User.java
-병원관련 CRUD 추가하였습니다.
-update의 경우 entity에 필드별로 update 메소드를 정의하고 service에서 메소드 체이닝을 이용하여 구현하였습니다. 
-delete의 경우 entity에 @SQLDelete 어노테이션을 붙여 soft delete로 진행하였습니다. 
-entity에 @Where로 조건을 걸어줘서 조회, 삭제 시에 soft delete된 항목이 보이지 않도록 했습니다.
=> [feat] 병원관련 CRUD 추가

src/main/java/com/example/petback/common/config/WebSecurityConfig.java, src/main/java/com/example/petback/feed/controller/FeedController.java, src/main/java/com/example/petback/feed/dto/FeedRequestDto.java, src/main/java/com/example/petback/feed/dto/FeedResponseDto.java, src/main/java/com/example/petback/feed/entity/Feed.java, src/main/java/com/example/petback/feed/repository/FeedRepository.java, src/main/java/com/example/petback/feed/service/FeedService.java, src/main/java/com/example/petback/feed/service/FeedServiceImpl.java, src/main/java/com/example/petback/user/entity/User.java
- Feed 관련된 기본적인 CRUD 완성
- 로그인 한 회원은 feed 생성이 가능
- 수정, 삭제는 작성자만 가능  (ADMIN은 추가해야?)
- feed 전체 / 상세 조회 확인 
- 이슈 : postman 조회 시 데이터 출력 안됨 -> @Where(clause = "is_deleted = true)
- @where 어노테이션 true 값을 false로 변경하여 확인함 -> @Where(clause = "is_deleted = false)
- 접근 허가 위해 WebSecurityConfig 코드 추가
- .requestMatchers("/api/feeds/**").permitAll()
- feed 상세 조회 (현재는 선택 조회라고 보면 됨) 시 더 보여줄 수 있는 정보가 나타나도록? 하면 ??? (추후 개발)
---
- PostMan으로 테스트 완료.
1. Feed 생성
2. Feed 조회
3. Feed 수정
4. Feed 삭재
=> [feat] Feed CRUD 추가

src/main/java/com/example/petback/common/domain/Address.java, src/main/java/com/example/petback/hospital/controller/HospitalController.java, src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java, src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/hospital/repository/HospitalRepository.java, src/main/java/com/example/petback/hospital/service/HospitalService.java, src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java, src/main/java/com/example/petback/reservation/ReservationStatusEnum.java, src/main/java/com/example/petback/reservation/controller/ReservationController.java, src/main/java/com/example/petback/reservation/dto/ReservationRequestDto.java, src/main/java/com/example/petback/reservation/dto/ReservationResponseDto.java, src/main/java/com/example/petback/reservation/entity/Reservation.java, src/main/java/com/example/petback/reservation/repository/ReservationRepository.java, src/main/java/com/example/petback/reservation/service/ReservationService.java, src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java, src/main/java/com/example/petback/reservationslot/controller/ReservationSlotController.java, src/main/java/com/example/petback/reservationslot/dto/ReservationSlotRequestDto.java, src/main/java/com/example/petback/reservationslot/dto/SelectReservationSlotRequestDto.java, src/main/java/com/example/petback/reservationslot/dto/SelectReservationSlotResponseDto.java, src/main/java/com/example/petback/reservationslot/entity/ReservationSlot.java, src/main/java/com/example/petback/reservationslot/repository/ReservationSlotRepository.java, src/main/java/com/example/petback/reservationslot/service/ReservationSlotService.java, src/main/java/com/example/petback/reservationslot/service/ReservationSlotServiceImpl.java, src/main/java/com/example/petback/user/dto/SignupRequestDto.java, src/main/java/com/example/petback/user/entity/User.java
- 병원측의 예약슬롯 추가, 삭제 기능
- 해당 날짜의 해당 병원에 대한 예약슬롯 조회기능
- 진료 예약, 취소, 조회기능
- 슬롯과 예약 엔티티는 다대일 관계로 설정(취소된 예약도 조회되게 하기위함)
- 현재 병원측에서 예약가능 날짜와 시간을 등록하면 환자가 그 slot들을 조회하여 예약을 할 수 있게 구성
- 추후 병원측에서 예약가능 날짜와 시간 등록하는 것을 자동화할 수 있는 로직을 추가해보면 좋을 것 같음
=> [Feat] 예약기능 추가

src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java, src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java, src/main/java/com/example/petback/hospitalspecies/entity/HospitalSpecies.java, src/main/java/com/example/petback/hospitalspecies/repository/HospitalSpeciesRepository.java, src/main/java/com/example/petback/hospitalsubject/entity/HospitalSubject.java, src/main/java/com/example/petback/hospitalsubject/repository/HospitalSubjectRepository.java, src/main/java/com/example/petback/species/SpeciesEnum.java, src/main/java/com/example/petback/species/entity/Species.java, src/main/java/com/example/petback/species/repository/SpeciesRepository.java, src/main/java/com/example/petback/species/service/SpeciesService.java, src/main/java/com/example/petback/subject/SubjectEnum.java, src/main/java/com/example/petback/subject/entity/Subject.java, src/main/java/com/example/petback/subject/repository/SubjectRepository.java, src/main/java/com/example/petback/subject/service/SubjectService.java, src/main/java/com/example/petback/user/entity/User.java
=> [Fix] 병원 생성, 수정시에 진료동물 종류, 진료과목 추가

src/main/java/com/example/petback/comment/controller/CommentController.java, src/main/java/com/example/petback/comment/dto/CommentRequestDto.java, src/main/java/com/example/petback/comment/dto/CommentResponseDto.java, src/main/java/com/example/petback/comment/entity/Comment.java, src/main/java/com/example/petback/comment/repository/CommentRepository.java, src/main/java/com/example/petback/comment/service/CommentService.java, src/main/java/com/example/petback/comment/service/CommentServiceImpl.java, src/main/java/com/example/petback/common/config/WebSecurityConfig.java, src/main/java/com/example/petback/feed/dto/FeedResponseDto.java, src/main/java/com/example/petback/feed/entity/Feed.java, src/main/java/com/example/petback/feed/service/FeedService.java, src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
feed 에 댓글을 달 수 있습니다.
수정 / 삭제도 됩니다.
삭제의 경우 feed id 를 참조할 필요 없이  (요청에 보낼 필요 없이) comment id 만으로 삭제 요청이 될 수 있을것 같은데.. 추후 수정을 해봅니다.
이렇게 요청이 귀찮게 됨.
=> [feat] feed 에 댓글기능 추가  (댓글 작성, 수정, 삭제)

src/main/java/com/example/petback/PetBackApplication.java, src/main/java/com/example/petback/notification/controller/NotificationController.java, src/main/java/com/example/petback/notification/dto/NotificationResponseDto.java, src/main/java/com/example/petback/notification/entity/Notification.java, src/main/java/com/example/petback/notification/repository/NotificationRepository.java, src/main/java/com/example/petback/notification/service/NotificationService.java, src/main/java/com/example/petback/notification/service/NotificationServiceImpl.java, src/main/java/com/example/petback/reservation/controller/ReservationController.java, src/main/java/com/example/petback/reservation/entity/Reservation.java, src/main/java/com/example/petback/reservation/event/EventPublisher.java, src/main/java/com/example/petback/reservation/event/ReservationEvent.java, src/main/java/com/example/petback/reservation/event/ReservationEventListener.java, src/main/java/com/example/petback/reservation/repository/ReservationRepository.java, src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java, src/main/java/com/example/petback/user/entity/User.java
- 첫 예약 성공 시에 비동기로 알람 객체 생성 이후 DB 저장 (비동기 로직에서 DB 저장은 권장되는 방법이 아니라 하여 수정 방법을 생각해 봐야 할 것 같습니다)
- 스케쥴러를 적용하여 예약 시간 5분 남았을 시에 자동 알람 생성 (상황에 맞게 추가 또는 수정 가능합니다)
=> [Feat] 알람 기능 구현

src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java
- TransactionSynchronizationManager 사용
=> [Refactor] JPA flush 제거

build.gradle, src/main/java/com/example/petback/chat/entity/ChatRoom.java, src/main/java/com/example/petback/common/domain/Address.java, src/main/java/com/example/petback/feed/entity/Feed.java, src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/hospital/repository/HospitalRepository.java, src/main/java/com/example/petback/hospitalspecies/entity/HospitalSpecies.java, src/main/java/com/example/petback/hospitalsubject/entity/HospitalSubject.java, src/main/java/com/example/petback/reservation/dto/ReservationRequestDto.java, src/main/java/com/example/petback/reservation/entity/Reservation.java, src/main/java/com/example/petback/reservationslot/entity/ReservationSlot.java, src/main/java/com/example/petback/species/entity/Species.java, src/main/java/com/example/petback/subject/entity/Subject.java, src/main/java/com/example/petback/user/entity/User.java, src/main/java/com/example/petback/user/repository/UserRepository.java, src/test/java/com/example/petback/hospital/controller/HospitalControllerTest.java, src/test/java/com/example/petback/reservation/controller/ReservationControllerTest.java
- 테스트환경용으로 h2db를 사용했습니다.
- 테스트환경용 application.yml을 사용하였고 슬랙에 해당내용 공유하였습니다.
- SpringBootTest로 작성하였습니다.
=> [Feat] 병원, 예약관련 테스트코드 작성하였습니다.

src/main/java/com/example/petback/comment/entity/Comment.java, src/main/java/com/example/petback/notification/entity/Notification.java, src/test/java/com/example/petback/notification/controller/NotificationControllerTest.java
- notification 테이블 복수형 변경
- comment 테이블 복수형 변경
- notification controller 테스트 코드 작성
=> [Feat] notification Controller 테스트 코드 작성

src/main/java/com/example/petback/common/config/CorsConfig.java, src/main/java/com/example/petback/common/config/WebSecurityConfig.java
cors 관련하여 CorsConfig를 생성하고, WebSecurityConfig에서 cors를 사용하도록 설정했습니다.
=> [Feat] Cors관련 설정 추가

src/main/java/com/example/petback/user/dto/SignupRequestDto.java
=> [Fix] 회원가입 시에 역할 추가

src/main/java/com/example/petback/user/dto/ProfileRequestDto.java, src/main/java/com/example/petback/user/dto/ProfileResponseDto.java, src/main/java/com/example/petback/user/entity/User.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java, src/test/java/com/example/petback/user/controller/UserControllerTest.java
=> feat: user 엔티티에 introduction 추가

src/main/java/com/example/petback/feed/controller/FeedController.java, src/main/java/com/example/petback/feed/dto/FeedResponseDto.java, src/main/java/com/example/petback/feed/repository/FeedRepository.java, src/main/java/com/example/petback/feed/service/FeedService.java, src/main/java/com/example/petback/feed/service/FeedServiceImpl.java, src/main/java/com/example/petback/user/entity/User.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java
=> feat: Feed 관련 내가 작성한 Feed만 조회하기 추가

src/main/java/com/example/petback/comment/entity/Comment.java, src/main/java/com/example/petback/common/advice/ApiResponseDto.java, src/main/java/com/example/petback/feed/entity/Feed.java, src/main/java/com/example/petback/feed/entity/FeedLike.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/hospitalspecies/entity/HospitalSpecies.java, src/main/java/com/example/petback/hospitalsubject/entity/HospitalSubject.java, src/main/java/com/example/petback/reservation/entity/Reservation.java, src/main/java/com/example/petback/reservationslot/entity/ReservationSlot.java, src/main/java/com/example/petback/review/entity/Review.java, src/main/java/com/example/petback/species/entity/Species.java, src/main/java/com/example/petback/subject/entity/Subject.java, src/main/java/com/example/petback/tip/entity/Tip.java, src/main/java/com/example/petback/tip/entity/TipLike.java, src/main/java/com/example/petback/user/dto/SignupRequestDto.java, src/main/java/com/example/petback/user/entity/User.java, src/main/java/com/example/petback/user/service/UserService.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java, src/test/java/com/example/petback/feed/controller/FeedControllerTest.java, src/test/java/com/example/petback/user/controller/UserControllerTest.java
- UserControllerTest 수정
- SignupRequestDto 필드 수정
- 불필요 Setter 제거
=> [Feat] access = AccessLevel.PROTECTED 옵션 추가

src/main/java/com/example/petback/chat/entity/ChatMessage.java, src/main/java/com/example/petback/chat/entity/ChatRoom.java, src/main/java/com/example/petback/comment/entity/Comment.java, src/main/java/com/example/petback/feed/dto/FeedResponseDto.java, src/main/java/com/example/petback/feed/entity/Feed.java, src/main/java/com/example/petback/feed/entity/FeedLike.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/reservation/entity/Reservation.java, src/main/java/com/example/petback/review/entity/Review.java, src/main/java/com/example/petback/user/dto/UserDto.java, src/main/java/com/example/petback/user/entity/User.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java
비질게~
// User 의 경우
// 피드, 피드 댓글, 피드 좋아요, 채팅방 메시지, 예약, 리뷰 > 탈퇴시 지워짐
// owner 의 경우
// 병원 > 탈퇴시 지워짐 species , subjects는?
// 채팅방, > 탈퇴시 안지워짐
=> 회원 탈퇴시 연관데이터 함께 삭제 (soft del)

src/main/java/com/example/petback/common/config/WebSecurityConfig.java, src/main/java/com/example/petback/common/exception/GlobalExceptionHandler.java, src/main/java/com/example/petback/notification/controller/NotificationController.java, src/main/java/com/example/petback/notification/dto/NotificationResponseDto.java, src/main/java/com/example/petback/notification/entity/Notification.java, src/main/java/com/example/petback/notification/repository/NotificationRepository.java, src/main/java/com/example/petback/notification/service/NotificationService.java, src/main/java/com/example/petback/notification/service/NotificationServiceImpl.java, src/main/java/com/example/petback/reservation/repository/ReservationRepository.java, src/main/java/com/example/petback/reservation/service/ReservationServiceImpl.java
- 알림 조회시 read여부
- dto에서 id 반환
- 조회시 알림생성 내림차순으로 조회
=> [Refactor] 알림기능 리팩터링

src/main/java/com/example/petback/chat/entity/ChatMessage.java, src/main/java/com/example/petback/chat/entity/ChatRoom.java, src/main/java/com/example/petback/comment/entity/Comment.java, src/main/java/com/example/petback/feed/entity/FeedLike.java, src/main/java/com/example/petback/hospital/OperatingDay.java, src/main/java/com/example/petback/hospital/dto/HospitalRequestDto.java, src/main/java/com/example/petback/hospital/dto/HospitalResponseDto.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/hospital/service/HospitalServiceImpl.java, src/main/java/com/example/petback/reservationslot/entity/ReservationSlot.java, src/main/java/com/example/petback/reservationslot/service/ReservationSlotScheduler.java, src/main/java/com/example/petback/tip/controller/TipContorller.java, src/main/java/com/example/petback/tip/entity/Tip.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java, src/test/java/com/example/petback/hospital/controller/HospitalControllerTest.java, src/test/java/com/example/petback/tip/controller/TipContorllerTest.java
- 병원 생성시 예약가능 슬롯을 자동 추가 (2개월로 설정)
- 매일 오전 4시에 2달 뒤에 해당하는 날짜의 병원 예약 가능 슬롯을 추가
=> [Feature]예약가능 슬롯 자동 추가

src/main/java/com/example/petback/common/exception/GlobalExceptionHandler.java, src/main/java/com/example/petback/common/jwt/JwtUtil.java, src/main/java/com/example/petback/common/security/JwtAuthorizationFilter.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java
- 리프레시 토큰 만료시 NoSuchElementException이 발생하는데, 이에 대한 처리를 authorization 필터에서 진행
=> [Refactor] refreshToken 만료시 exception handling

src/main/java/com/example/petback/chat/controller/ChatController.java, src/main/java/com/example/petback/chat/dto/RoomDto.java, src/main/java/com/example/petback/chat/entity/ChatMessage.java, src/main/java/com/example/petback/chat/repository/ChatRoomRepository.java, src/main/java/com/example/petback/chat/service/ChatService.java, src/main/java/com/example/petback/chat/service/ChatServiceImpl.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java
=> refactor: 채팅방 삭제

src/main/java/com/example/petback/comment/dto/CommentResponseDto.java, src/main/java/com/example/petback/comment/entity/Comment.java, src/main/java/com/example/petback/comment/service/CommentServiceImpl.java, src/main/java/com/example/petback/feed/dto/FeedResponseDto.java, src/main/java/com/example/petback/feed/entity/Feed.java, src/main/java/com/example/petback/feed/entity/FeedLike.java, src/main/java/com/example/petback/hospital/entity/Hospital.java, src/main/java/com/example/petback/notification/entity/Notification.java, src/main/java/com/example/petback/reservation/entity/Reservation.java, src/main/java/com/example/petback/review/entity/Review.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java, src/test/java/com/example/petback/comment/controller/FeedCommentControllerTest.java
=> [Feature] Hard Delete로 변경

src/main/java/com/example/petback/hospital/controller/HospitalController.java, src/main/java/com/example/petback/reservationslot/service/ReservationSlotScheduler.java, src/main/java/com/example/petback/tip/controller/TipContorller.java, src/main/java/com/example/petback/tip/entity/Tip.java, src/main/java/com/example/petback/tip/entity/TipLike.java, src/main/java/com/example/petback/tip/repository/TipLikeRepository.java, src/main/java/com/example/petback/tip/service/TipService.java, src/main/java/com/example/petback/tip/service/TipServiceImpl.java, src/test/java/com/example/petback/tip/controller/TipContorllerTest.java
- 좋아요 로직 수정
- content 길이 제한 수정
- 좋아요 생성시 builder 패턴 사용
=> [Refactor] tip 일부 수정

src/main/java/com/example/petback/user/dto/UserDto.java, src/main/java/com/example/petback/user/entity/User.java, src/main/java/com/example/petback/user/repository/UserRepository.java, src/main/java/com/example/petback/user/service/UserServiceImpl.java
@where 달고도 됩니다.
이제 softDelete된 다른 데이터 연결을 해보면되겠네요
=> [Refactor] 탈퇴 회원 복구로직 수정

src/main/java/com/example/petback/feed/controller/FeedController.java, src/main/java/com/example/petback/feed/repository/FeedRepository.java, src/main/java/com/example/petback/feed/service/FeedService.java, src/main/java/com/example/petback/feed/service/FeedServiceImpl.java
feed 좋아요 순서로 조회 구현하고 캐싱처리 했습니다.
feedLike 필드의 size로 조건문을 주기 위해 native query 사용하였습니다.
=> [Feature] 피드 좋아요 순 조회 추가 및 캐싱처리

build.gradle, src/main/java/com/example/petback/common/controller/HealthCheckController.java, src/main/java/com/example/petback/tip/controller/TipContorller.java, src/main/java/com/example/petback/tip/repository/TipRepository.java, src/main/java/com/example/petback/tip/service/TipService.java, src/main/java/com/example/petback/tip/service/TipServiceImpl.java, src/main/java/com/example/petback/user/controller/UserController.java
- sout 제거하고 log로 변경
- QClass 한번에 생성 안되는 문제 해결
- 키워드 별 검색에도 캐싱 적용
=> [Feature] 팁 제목/내용 별 검색 기능 추가
